### PR TITLE
fuggit

### PR DESCRIPTION
**Pull request by WarrenBuffering**
send it

### CODE REVIEW

**Comment by WarrenBuffering** [comment]
lgtm

**Review by WarrenBuffering — COMMENTED** [review]
lgtm

**Comment by PhearZero** [comment]
Depreciation notice: 

Since the advent of HTMX, languages no longer need spinning loaders. Hypermedia can simply return the Error as hypermedia, greatly simplifying current strategies.

We know this can be painful for advocates of loading spinners and JavaScript. @WarrenBuffering has been working directly with the team at SA and has valuable resources to help you transition.

We want to personally thank @trvswgnr and @1cg for finally defeating JavaScript.

🦀

**Comment by 1cg** [comment]
lgtm wtf

**Comment by trvswgnr** [comment]
it has never been more over than it is right now, in this moment

**Pull request closed without merging**
